### PR TITLE
All the flavors!

### PR DESCRIPTION
**Pull request by Itxaka**
Part of https://github.com/rancher-sandbox/cOS-toolkit/issues/1244

Not to be merged until https://github.com/rancher-sandbox/cOS-toolkit/pull/1321 is merged

### CODE REVIEW

**Review by mudler — APPROVED** [review]

**Comment by mudler** [comment]
oh well, we could keep maybe both for a while? (so we can compare, etc)

**Comment by Itxaka** [comment]
Thats what I thought, I dont think its too much to have both of them (even the other flavors too) right? Like it takes one minute to build green which is huge and then its just static pages?? Maybe we should just have all of them, its really nice to have the package browser!

**Review by mjura — APPROVED** [review]
LGTM

**Review by mudler — APPROVED** [review]
lookin good!

**Pull request merged**
